version: 2.1
orbs:
  go: circleci/go@1.7.1
jobs:
  build:
    working_directory: ~/Zocket-Task-1-2-3-4/Task-2
    executor:
      name: go/default
      tag: "1.19"
    steps:
      - checkout:
          path: ~/Zocket-Task-1-2-3-4
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Run tests
          command: go test